version: '3.8'
services:
  dev-db:
    image: postgres:13
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgress
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
    networks:
      - Rahul
  minio:
    image: quay.io/minio/minio
    ports:
      - 9000:9000
      - 9090:9090
    volumes:
      - C:\minio\data:/data
    environment:
      - MINIO_ROOT_USER=ROOTUSER
      - MINIO_ROOT_PASSWORD=CHANGEME123
    command: server /data --console-address ":9090"
 
    networks:
      - Rahul
networks:
  Rahul:
